<?php declare(strict_types=1);
/**
 * OneDev_OksanaSerhiienko
 */

use OneDev\CheckoutHero\Magewire\CustomerInfo;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var CustomerInfo $magewire */

?>

<div class="checkout-step customer-info">
    <h2>Hello <?= $escaper->escapeHtml($magewire->firstname) . ' ' . $escaper->escapeHtml($magewire->lastname) ?></h2>
    <p>Thanks for shopping with us.</p>
</div>
